version: "3"
services:
  noq-dev-shared-prod-1-api:
    image: "940552945933.dkr.ecr.us-west-2.amazonaws.com/prod-registry-api:prod"
    ports:
      - "8092:8092"
      - "2222:2222"
    environment:
      - SETUPTOOLS_USE_DISTUTILS=stdlib
      - CONFIG_LOCATION=s3://noq-dev-shared-prod-1-tenant-configuration-store/shared/prod.1.config.yaml
    command: python api/__main__.py
    logging:
      driver: awslogs
      options:
        awslogs-group: noq-dev-shared-prod-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: web

  noq-dev-shared-prod-1-celery:
    image: "940552945933.dkr.ecr.us-west-2.amazonaws.com/prod-registry-celery:prod"
    ports:
      - "2223:2223"
    environment:
      - SETUPTOOLS_USE_DISTUTILS=stdlib
      - CONFIG_LOCATION=s3://noq-dev-shared-prod-1-tenant-configuration-store/shared/prod.1.config.yaml
      - CELERY_LOG_LEVEL=DEBUG
      - CELERY_CONCURRENCY=16
    command: celery -A common.celery_tasks.celery_tasks worker -l DEBUG -B -E --concurrency=8
    logging:
      driver: awslogs
      options:
        awslogs-group: noq-dev-shared-prod-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: celery