version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: arn:aws:iam::940552945933:role/noq-dev-shared-prod-1-ecsTaskExecutionRole
  task_size:
    cpu_limit: 2048
    mem_limit: 4GB
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0335e107c814d63f5
        - subnet-06b4ff38d90fa1b9b
      security_groups:
        - sg-0e7a1ca3c697feb53
      assign_public_ip: DISABLED