executionRoleArn: arn:aws:iam::940552945933:role/noq-dev-shared-prod-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: []
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: noq-dev-shared-prod-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: celery-flower
    portMappings:
      - hostPort: 7071
        protocol: tcp
        containerPort: 7071
    entryPoint:
      - /bin/sh
      - "-c"
      - "python /app/common/celery_tasks/run.py"
    linuxParameters:
      devices: []
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://noq-dev-shared-prod-1-tenant-configuration-store/shared/prod.1.config.yaml
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: CELERY_FLOWER
      - name: STAGE
        value: prod
    dnsServers: []
    mountPoints: []
    dockerSecurityOptions: []
    volumesFrom: []
    image: 940552945933.dkr.ecr.us-west-2.amazonaws.com/shared-prod-registry-api:prod
    essential: true
    links: []
    extraHosts: []
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: noq-dev-shared-prod-1-celery-flower
placementConstraints: []
memory: "512"
taskRoleArn: arn:aws:iam::940552945933:role/noq-dev-shared-prod-1-ecsTaskRole
family: noq-dev-shared-prod-1-celery-flower
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: "256"
volumes: []
