http:
  routers:
    cloudumi_frontend:
      service: cloudumi_frontend
      rule: "PathPrefix(`/`)"
      priority: 1 # Lowest priority, last thing we will match
    cloudumi_api:
      service: cloudumi_api
      rule: "PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/noauth`)"
    cloudumi_saml:
      service: cloudumi_saml
      rule: "PathPrefix(`/saml`)"

  services:
    cloudumi_healthcheck:
      loadbalancer:
        servers:
          - url: "http://127.0.0.1:8090/"
    cloudumi_saml:
      loadbalancer:
        servers:
          - url: "http://127.0.0.1:8091/"
    cloudumi_api:
      loadbalancer:
        servers:
          - url: "http://127.0.0.1:8092/"
    cloudumi_frontend:
      loadbalancer:
        servers:
          - url: "http://127.0.0.1:3000/"
