version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: arn:aws:iam::259868150464:role/noq-dev-shared-staging-1-ecsTaskExecutionRole
  task_size:
    cpu_limit: 2048
    mem_limit: 4GB
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-08762a28231c59d36
        - subnet-0812d20b4152bac8f
      security_groups:
        - sg-05f33ef672dfcbd83
      assign_public_ip: ENABLED