"""migration

Revision ID: 0d66940df8e4
Revises: bc4d17a5423b
Create Date: 2023-06-24 10:12:19.389389

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0d66940df8e4"
down_revision = "bc4d17a5423b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "github_installs_installation_id_key", "github_installs", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "github_installs_installation_id_key", "github_installs", ["installation_id"]
    )
    # ### end Alembic commands ###
