"""migration

Revision ID: 117c61ccbcdd
Revises: 60876068e66a
Create Date: 2023-01-28 13:32:58.440888

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "117c61ccbcdd"
down_revision = "60876068e66a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_tenant_install_relationships",
        "slack_bots_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "slack_tenant_install_relationships_slack_bots_id_fkey",
        "slack_tenant_install_relationships",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "slack_tenant_install_relationships_slack_bots_id_fkey",
        "slack_tenant_install_relationships",
        "slack_bots",
        ["slack_bots_id"],
        ["id"],
    )
    op.alter_column(
        "slack_tenant_install_relationships",
        "slack_bots_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
