"""migration

Revision ID: 146467e92abd
Revises: 8aa283791be5
Create Date: 2023-03-12 16:16:40.614999

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "146467e92abd"
down_revision = "8aa283791be5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("role_access", sa.Column("created_by", sa.String(), nullable=True))
    op.add_column("role_access", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("role_access", sa.Column("deleted", sa.Boolean(), nullable=True))
    op.add_column("role_access", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_access", "deleted_at")
    op.drop_column("role_access", "deleted")
    op.drop_column("role_access", "created_at")
    op.drop_column("role_access", "created_by")
    # ### end Alembic commands ###
