"""migration

Revision ID: 176105895eba
Revises: 82168b7de4c8
Create Date: 2023-01-30 05:48:12.309312

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '176105895eba'
down_revision = '82168b7de4c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_tenant_install_relationships', 'slack_bots_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'slack_tenant_install_relationships', 'slack_bots', ['slack_bots_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slack_tenant_install_relationships', type_='foreignkey')
    op.alter_column('slack_tenant_install_relationships', 'slack_bots_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
