"""migration

Revision ID: 229a22bfde4b
Revises: 117c61ccbcdd
Create Date: 2023-01-28 13:38:49.316662

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "229a22bfde4b"
down_revision = "117c61ccbcdd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
