"""migration

Revision ID: 2818563ad73b
Revises: 66bfd6f60a98
Create Date: 2023-05-31 14:03:21.738039

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2818563ad73b"
down_revision = "66bfd6f60a98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("installation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("installation_id"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.create_table(
        "github_oauth_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state"),
        sa.UniqueConstraint("tenant_id"),
    )
    op.create_unique_constraint(None, "github_installs", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "github_installs", type_="unique")
    op.drop_table("github_oauth_states")
    op.drop_table("github_installs")
    # ### end Alembic commands ###
