"""migration

Revision ID: 2921da1e8990
Revises: 7ce3ae9ed8aa
Create Date: 2023-08-11 15:54:17.726694

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2921da1e8990"
down_revision = "7ce3ae9ed8aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "iambic_template", sa.Column("friendly_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("iambic_template", "friendly_name")
    # ### end Alembic commands ###
