"""migration

Revision ID: 31417e25bd38
Revises: 28685f8cf18b
Create Date: 2023-02-19 14:54:45.499709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31417e25bd38"
down_revision = "28685f8cf18b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "aws_account", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(None, "identity_role", "tenant", ["tenant_id"], ["id"])
    op.add_column("request", sa.Column("request_method", sa.String(), nullable=True))
    op.add_column("request", sa.Column("slack_username", sa.String(), nullable=True))
    op.add_column("request", sa.Column("slack_email", sa.String(), nullable=True))
    op.add_column("request", sa.Column("duration", sa.String(), nullable=True))
    op.add_column("request", sa.Column("resource_type", sa.String(), nullable=True))
    op.add_column("request", sa.Column("request_notes", sa.String(), nullable=True))
    op.add_column("request", sa.Column("slack_channel_id", sa.String(), nullable=True))
    op.add_column("request", sa.Column("slack_message_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "request", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "role_access", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "role_access", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "role_access", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "slack_tenant_install_relationships", "tenant", ["tenant_id"], ["id"]
    )
    op.create_foreign_key(
        None, "slack_tenant_oauth_relationships", "tenant", ["tenant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slack_tenant_oauth_relationships", type_="foreignkey")
    op.drop_constraint(None, "slack_tenant_install_relationships", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "request", type_="foreignkey")
    op.drop_column("request", "slack_message_id")
    op.drop_column("request", "slack_channel_id")
    op.drop_column("request", "request_notes")
    op.drop_column("request", "resource_type")
    op.drop_column("request", "duration")
    op.drop_column("request", "slack_email")
    op.drop_column("request", "slack_username")
    op.drop_column("request", "request_method")
    op.drop_constraint(None, "identity_role", type_="foreignkey")
    op.drop_constraint(None, "aws_account", type_="foreignkey")
    # ### end Alembic commands ###
