"""migration

Revision ID: 384801ea9ecd
Revises: 7744ee2c586d
Create Date: 2023-05-08 19:53:04.449878

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "384801ea9ecd"
down_revision = "7744ee2c586d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "aws_account", "tenant", ["tenant_id"], ["id"])
    op.create_unique_constraint(None, "github_installs", ["id"])
    op.create_unique_constraint(None, "github_oauth_states", ["tenant_id"])
    op.create_foreign_key(None, "identity_role", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(None, "request", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "role_access", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "role_access", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "role_access", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "slack_tenant_install_relationships", "tenant", ["tenant_id"], ["id"]
    )
    op.create_foreign_key(
        None, "slack_tenant_oauth_relationships", "tenant", ["tenant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slack_tenant_oauth_relationships", type_="foreignkey")
    op.drop_constraint(None, "slack_tenant_install_relationships", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "request", type_="foreignkey")
    op.drop_constraint(None, "identity_role", type_="foreignkey")
    op.drop_constraint(None, "github_oauth_states", type_="unique")
    op.drop_constraint(None, "github_installs", type_="unique")
    op.drop_constraint(None, "aws_account", type_="foreignkey")
    # ### end Alembic commands ###
