"""migration

Revision ID: 416377939322
Revises: 449bb0f96c04
Create Date: 2023-01-28 12:26:58.813273

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "416377939322"
down_revision = "449bb0f96c04"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_tenant_oauth_relationships",
        sa.Column("created_by", sa.String(), nullable=True),
    )
    op.add_column(
        "slack_tenant_oauth_relationships",
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "slack_tenant_oauth_relationships",
        sa.Column("deleted", sa.Boolean(), nullable=True),
    )
    op.drop_constraint(
        "uq_slack_tenant_oauth_id", "slack_tenant_oauth_relationships", type_="unique"
    )
    op.create_unique_constraint(
        "uq_slack_tenant", "slack_tenant_oauth_relationships", ["tenant_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_slack_tenant", "slack_tenant_oauth_relationships", type_="unique"
    )
    op.create_unique_constraint(
        "uq_slack_tenant_oauth_id",
        "slack_tenant_oauth_relationships",
        ["tenant_id", "oauth_id"],
    )
    op.drop_column("slack_tenant_oauth_relationships", "deleted")
    op.drop_column("slack_tenant_oauth_relationships", "created_at")
    op.drop_column("slack_tenant_oauth_relationships", "created_by")
    # ### end Alembic commands ###
