"""migration

Revision ID: 449bb0f96c04
Revises: 51f8839d04e2
Create Date: 2023-01-28 12:06:37.702620

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "449bb0f96c04"
down_revision = "51f8839d04e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenant_name"), "tenant", ["name"], unique=False)
    op.create_table(
        "slack_tenant_oauth_relationships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("oauth_id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "oauth_id", name="uq_slack_tenant_oauth_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("slack_tenant_oauth_relationships")
    op.drop_index(op.f("ix_tenant_name"), table_name="tenant")
    op.drop_table("tenant")
    # ### end Alembic commands ###
