"""migration

Revision ID: 52712239dae8
Revises: ea58c8598995
Create Date: 2023-01-24 14:26:21.073269

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52712239dae8"
down_revision = "ea58c8598995"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
