"""migration

Revision ID: 5522fa629889
Revises: e86c25caebc5
Create Date: 2023-01-31 14:24:23.078978

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5522fa629889'
down_revision = 'e86c25caebc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('pull_request_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'pull_request_url')
    # ### end Alembic commands ###
