"""migration

Revision ID: 60876068e66a
Revises: 967eb8274530
Create Date: 2023-01-28 13:26:29.328340

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "60876068e66a"
down_revision = "967eb8274530"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
