"""migration

Revision ID: 66bfd6f60a98
Revises: b80e7f0cafc5
Create Date: 2023-05-17 15:31:50.195169

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "66bfd6f60a98"
down_revision = "b80e7f0cafc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant",
        sa.Column("iambic_templates_last_parsed", sa.DateTime(), nullable=True),
    )
    op.create_table(
        "iambic_template",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("repo_name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("template_type", sa.String(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "aws",
                "azure_ad",
                "google_workspace",
                "okta",
                name="ProviderEnum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "iambic_tmplt_tenant_repo_file_idx",
        "iambic_template",
        ["tenant_id", "repo_name", "file_path"],
        unique=False,
    )
    op.create_index(
        "iambic_tmplt_tp_resource_idx",
        "iambic_template",
        ["tenant_id", "provider", "resource_type"],
        unique=False,
    )
    op.create_index(
        "iambic_tmplt_tp_resource_w_id_idx",
        "iambic_template",
        ["tenant_id", "provider", "resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "iambic_tmplt_tp_template_type_idx",
        "iambic_template",
        ["tenant_id", "provider", "template_type"],
        unique=False,
    )
    op.create_index(
        "iambic_tmplt_tt_w_resource_id_idx",
        "iambic_template",
        ["tenant_id", "template_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        "uix_iambic_tmplt_idx",
        "iambic_template",
        [
            "tenant_id",
            "provider",
            "resource_type",
            "resource_id",
            "template_type",
            "repo_name",
        ],
        unique=True,
    )
    op.create_table(
        "iambic_template_content",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("iambic_template_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iambic_template_id"],
            ["iambic_template.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uix_tenant_template_content_idx",
        "iambic_template_content",
        ["tenant_id", "iambic_template_id"],
        unique=True,
    )
    op.create_table(
        "iambic_template_provider_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("iambic_template_id", sa.UUID(), nullable=True),
        sa.Column("tenant_provider_definition_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["iambic_template_id"],
            ["iambic_template.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_provider_definition_id"],
            ["tenant_provider_definition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "itpd_provider_def_idx",
        "iambic_template_provider_definition",
        ["tenant_provider_definition_id"],
        unique=False,
    )
    op.create_index(
        "itpd_template_and_provider_def_idx",
        "iambic_template_provider_definition",
        ["iambic_template_id", "tenant_provider_definition_id"],
        unique=False,
    )
    op.create_index(
        "itpd_template_id_idx",
        "iambic_template_provider_definition",
        ["iambic_template_id"],
        unique=False,
    )
    op.create_index(
        "uix_tp_idx",
        "tenant_provider",
        ["tenant_id", "provider", "sub_type"],
        unique=True,
    )
    op.create_index(
        "uix_tpd_idx",
        "tenant_provider_definition",
        ["tenant_id", "provider", "sub_type", "name"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant", "iambic_templates_last_parsed")
    op.drop_index("uix_tpd_idx", table_name="tenant_provider_definition")
    op.drop_index("uix_tp_idx", table_name="tenant_provider")
    op.drop_index(
        "itpd_template_id_idx", table_name="iambic_template_provider_definition"
    )
    op.drop_index(
        "itpd_template_and_provider_def_idx",
        table_name="iambic_template_provider_definition",
    )
    op.drop_index(
        "itpd_provider_def_idx", table_name="iambic_template_provider_definition"
    )
    op.drop_table("iambic_template_provider_definition")
    op.drop_index(
        "uix_tenant_template_content_idx", table_name="iambic_template_content"
    )
    op.drop_table("iambic_template_content")
    op.drop_index("uix_iambic_tmplt_idx", table_name="iambic_template")
    op.drop_index("iambic_tmplt_tt_w_resource_id_idx", table_name="iambic_template")
    op.drop_index("iambic_tmplt_tp_template_type_idx", table_name="iambic_template")
    op.drop_index("iambic_tmplt_tp_resource_w_id_idx", table_name="iambic_template")
    op.drop_index("iambic_tmplt_tp_resource_idx", table_name="iambic_template")
    op.drop_index("iambic_tmplt_tenant_repo_file_idx", table_name="iambic_template")
    op.drop_table("iambic_template")
    # ### end Alembic commands ###
