"""migration

Revision ID: 71cb738c24be
Revises: 31417e25bd38
Create Date: 2023-02-19 14:57:56.387541

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71cb738c24be"
down_revision = "31417e25bd38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request", sa.Column("branch_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("request", "branch_name")
    # ### end Alembic commands ###
