"""migration

Revision ID: 7744ee2c586d
Revises: 9166a0f11d02
Create Date: 2023-05-08 16:38:51.593014

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7744ee2c586d"
down_revision = "9166a0f11d02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_installs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "github_oauth_states",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state"),
    )
    op.create_foreign_key(None, "aws_account", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(None, "identity_role", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(None, "request", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "role_access", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "role_access", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "role_access", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "slack_tenant_install_relationships", "tenant", ["tenant_id"], ["id"]
    )
    op.create_foreign_key(
        None, "slack_tenant_oauth_relationships", "tenant", ["tenant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "slack_tenant_oauth_relationships", type_="foreignkey")
    op.drop_constraint(None, "slack_tenant_install_relationships", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "request", type_="foreignkey")
    op.drop_constraint(None, "identity_role", type_="foreignkey")
    op.drop_constraint(None, "aws_account", type_="foreignkey")
    op.drop_table("github_oauth_states")
    op.drop_table("github_installs")
    # ### end Alembic commands ###
