"""migration

Revision ID: 82168b7de4c8
Revises: 229a22bfde4b
Create Date: 2023-01-30 05:43:26.920963

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '82168b7de4c8'
down_revision = '229a22bfde4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
