"""migration

Revision ID: 967eb8274530
Revises: 2ab32b844ea0
Create Date: 2023-01-28 13:22:29.383764

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "967eb8274530"
down_revision = "2ab32b844ea0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
