"""migration

Revision ID: a32a9a9e6815
Revises: 176105895eba
Create Date: 2023-01-30 06:11:38.946502

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a32a9a9e6815'
down_revision = '176105895eba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
