"""migration

Revision ID: b2877e6bce73
Revises: ea58c8598995
Create Date: 2023-01-24 14:32:26.133570

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b2877e6bce73"
down_revision = "ea58c8598995"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("identity_role", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "identity_role", "tenant", ["tenant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "identity_role", type_="foreignkey")
    op.drop_column("identity_role", "tenant_id")
    # ### end Alembic commands ###
