"""migration

Revision ID: b80e7f0cafc5
Revises: 839937239244
Create Date: 2023-05-08 14:01:55.958874

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b80e7f0cafc5"
down_revision = "9166a0f11d02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_provider",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "aws", "google_workspace", "okta", "azure_ad", name="ProviderEnum"
            ),
            nullable=False,
        ),
        sa.Column("sub_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("tp_tenant_idx", "tenant_provider", ["tenant_id"], unique=False)
    op.create_table(
        "tenant_provider_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            postgresql.ENUM(
                "aws", "google_workspace", "okta", "azure_ad", name="ProviderEnum"
            ),
            nullable=False,
        ),
        sa.Column("sub_type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "tpd_tenant_idx", "tenant_provider_definition", ["tenant_id"], unique=False
    )
    op.create_index(
        "tpd_tenant_provider_idx",
        "tenant_provider_definition",
        ["tenant_id", "provider"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("tpd_tenant_provider_idx", table_name="tenant_provider_definition")
    op.drop_index("tpd_tenant_idx", table_name="tenant_provider_definition")
    op.drop_table("tenant_provider_definition")
    op.drop_index("tp_tenant_idx", table_name="tenant_provider")
    op.drop_table("tenant_provider")
    # ### end Alembic commands ###
