"""migration

Revision ID: b80f0858b773
Revises: 71cb738c24be
Create Date: 2023-02-20 13:43:41.837400

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b80f0858b773"
down_revision = "71cb738c24be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group_memberships", sa.Column("updated_by", sa.String(), nullable=True)
    )
    op.add_column(
        "group_memberships", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column("groups", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("groups", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("request", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("request", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "request_comment", sa.Column("updated_by", sa.String(), nullable=True)
    )
    op.add_column(
        "request_comment", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "slack_tenant_install_relationships",
        sa.Column("updated_by", sa.String(), nullable=True),
    )
    op.add_column(
        "slack_tenant_install_relationships",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "slack_tenant_oauth_relationships",
        sa.Column("updated_by", sa.String(), nullable=True),
    )
    op.add_column(
        "slack_tenant_oauth_relationships",
        sa.Column("updated_at", sa.DateTime(), nullable=True),
    )
    op.add_column("tenant", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("tenant", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("updated_by", sa.String(), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "updated_by")
    op.drop_column("tenant", "updated_at")
    op.drop_column("tenant", "updated_by")
    op.drop_column("slack_tenant_oauth_relationships", "updated_at")
    op.drop_column("slack_tenant_oauth_relationships", "updated_by")
    op.drop_column("slack_tenant_install_relationships", "updated_at")
    op.drop_column("slack_tenant_install_relationships", "updated_by")
    op.drop_column("request_comment", "updated_at")
    op.drop_column("request_comment", "updated_by")
    op.drop_column("request", "updated_at")
    op.drop_column("request", "updated_by")
    op.drop_column("groups", "updated_at")
    op.drop_column("groups", "updated_by")
    op.drop_column("group_memberships", "updated_at")
    op.drop_column("group_memberships", "updated_by")
    # ### end Alembic commands ###
