"""migration

Revision ID: bcfc5e8f10ce
Revises: a32a9a9e6815
Create Date: 2023-01-30 06:21:01.330524

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'bcfc5e8f10ce'
down_revision = 'a32a9a9e6815'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
