"""migration

Revision ID: bf4604589d9b
Revises: d020f1927b9e
Create Date: 2023-02-12 05:30:05.833109

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf4604589d9b"
down_revision = "d020f1927b9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "aws_account", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(None, "identity_role", "tenant", ["tenant_id"], ["id"])
    op.create_foreign_key(
        None, "role_access", "groups", ["group_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "role_access", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "role_access", "tenant", ["tenant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "role_access", type_="foreignkey")
    op.drop_constraint(None, "identity_role", type_="foreignkey")
    op.drop_constraint(None, "aws_account", type_="foreignkey")
    # ### end Alembic commands ###
