"""migration

Revision ID: e86c25caebc5
Revises: bcfc5e8f10ce
Create Date: 2023-01-30 06:28:25.807556

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'e86c25caebc5'
down_revision = 'bcfc5e8f10ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
