"""migration

Revision ID: ec281b2d92ba
Revises: bf4604589d9b
Create Date: 2023-02-12 11:02:03.956423

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec281b2d92ba"
down_revision = "bf4604589d9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE managed_by_enum AS ENUM ('MANUAL', 'SCIM')")
    op.add_column(
        "groups",
        sa.Column(
            "managed_by",
            sa.Enum("MANUAL", "SCIM", name="managed_by_enum"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "managed_by",
            sa.Enum("MANUAL", "SCIM", name="managed_by_enum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "managed_by")
    op.drop_column("groups", "managed_by")
    op.execute("DROP TYPE managed_by_enum")
    # ### end Alembic commands ###
