"""migration

Revision ID: ef3f15e6b7f3
Revises: 28c4ecde93e9
Create Date: 2023-07-06 08:27:00.383949

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ef3f15e6b7f3"
down_revision = "28c4ecde93e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "change_type", sa.Column("template_attribute", sa.String(), nullable=True)
    )
    op.add_column(
        "change_type",
        sa.Column(
            "apply_attr_behavior",
            postgresql.ENUM(
                "Append",
                "Merge",
                "Replace",
                name="ApplyAttrBehaviorEnum",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "change_type",
        sa.Column(
            "provider_definition_field",
            postgresql.ENUM(
                "Allow One",
                "Allow Multiple",
                "Allow None",
                name="ProviderDefinitionFieldEnum",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.drop_column("request_type", "provider_definition_field")
    op.drop_column("request_type", "apply_attr_behavior")
    op.drop_column("request_type", "template_attribute")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_type",
        sa.Column(
            "template_attribute", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "request_type",
        sa.Column(
            "apply_attr_behavior",
            postgresql.ENUM("Append", "Merge", "Replace", name="ApplyAttrBehaviorEnum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "request_type",
        sa.Column(
            "provider_definition_field",
            postgresql.ENUM(
                "Allow One",
                "Allow Multiple",
                "Allow None",
                name="ProviderDefinitionFieldEnum",
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("change_type", "provider_definition_field")
    op.drop_column("change_type", "apply_attr_behavior")
    op.drop_column("change_type", "template_attribute")
    # ### end Alembic commands ###
