exclude: "^docs/gitbook/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "^docs/gitbook/|^helm/cloudumi|cdk/resources/create_config_lambda/config.yaml|^deploy"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: ["--exclude", "common/models.py,identity/lib/groups/models.py"]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: "5.6.4" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort # Run `isort -rc <filepath>` to autofix
        pass_filenames: true
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.7.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude: "^helm/consoleme"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.24.0
    hooks:
      - id: eslint
        args:
          [
            "--fix",
            "--max-warnings",
            "0",
            "--resolve-plugins-relative-to",
            "./frontend",
            "-c",
            "./frontend/.eslintrc",
            "--ignore-path",
            "./frontend/.eslintignore",
          ]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: env CONFIG_LOCATION=common/tests/test_configuration.yaml pytest
        args: ["common/tests"]
        language: system
        pass_filenames: false
        always_run: true

      - id: python-bandit-vulnerability-check
        name: bandit
        entry: bandit
        args: ["--ini", "tox.ini", "-r", "cloudumi"]
        language: system
        pass_filenames: false
