exclude: "^docs/gitbook/"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: "^docs/gitbook/|^helm/cloudumi|cdk/resources/create_config_lambda/config.yaml|^deploy"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--exclude", "common/models.py,identity/lib/groups/models.py"]

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: "5.10.1" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort # Run `isort -rc <filepath>` to autofix
        pass_filenames: true
        args: ["--profile", "black"]

  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
      - id: python-no-log-warn

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: "^helm/consoleme"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt
      - id: terraform_tfsec
        args:
          - >
            --args=-e aws-dynamodb-table-customer-key,aws-dynamodb-enable-at-rest-encryption,aws-iam-no-policy-wildcards,aws-vpc-no-public-ingress-sgr,aws-ecs-enable-container-insight,aws-cloudwatch-log-group-customer-key,aws-s3-encryption-customer-key,aws-sqs-enable-queue-encryption,aws-sns-enable-topic-encryption
      - id: terraform_validate
      # TODO (ccastrapel): Add additional checks when we're ready for them
      # - id: terrascan
      # - id: checkov
      #   args: ["--skip-path", "env*"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0
    hooks:
      - id: eslint
        args:
          [
            "--fix",
            "--max-warnings",
            "0",
            "--resolve-plugins-relative-to",
            "./frontend",
            "-c",
            "./frontend/.eslintrc",
            "--ignore-path",
            "./frontend/.eslintignore",
          ]
  - repo: local
    hooks:
      #      - id: pytest
      #        name: pytest
      #        entry: env CONFIG_LOCATION=common/tests/test_configuration.yaml pytest
      #        args: ["common/tests"]
      #        language: system
      #        pass_filenames: false
      #        always_run: true

      - id: python-bandit-vulnerability-check
        name: bandit
        entry: bandit
        args: ["--ini", "tox.ini", "-r", "cloudumi"]
        language: system
        pass_filenames: false
