# Use this traefik configuration when you want to run services in a container, and have traefik use TLS for all traffic

version: "3.8"

services:
  reverse-proxy:
    image: traefik
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
      - ./cloudumi_traefik/config_docker_tls:/etc/traefik/
    labels:
      - traefik.enable=false

volumes:
  certs:
