version: "3.8"

services:
  reverse-proxy:
    image: traefik
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
      - ./cloudumi_traefik/config_localhost:/etc/traefik/
    labels:
      - traefik.enable=false

volumes:
  certs:
