# noq file -p arn:aws:iam::759357822767:role/NoqSaasRoleLocalDev arn:aws:iam::759357822767:role/NoqSaasRoleLocalDev -f
# docker-compose -f docker-compose.yaml -f deploy/docker-compose-dependencies.yaml down && docker-compose -f docker-compose.yaml -f deploy/docker-compose-dependencies.yaml build && docker-compose -f docker-compose.yaml -f deploy/docker-compose-dependencies.yaml up --force-recreate
version: "3"
services:
  cloudumi-preflight:
    container_name: cloudumi-preflight
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.aws:/root/.aws:cached
      # - .:/app:cached
      # Don't allow node_modules to be a volume in container
      - ./common/scripts/preflight_tests.sh:/app/common/scripts/preflight_tests.sh:cached
      - /app/frontend/node_modules/
      - /app/ui/node_modules/
    ports:
      - 8092:8092
    depends_on:
      - cloudumi-redis
      - cloudumi-dynamodb
      - cloudumi-pg
    links:
      - cloudumi-redis
      - cloudumi-dynamodb
      - cloudumi-pg
    command: bash -c 'common/scripts/preflight_tests.sh'
    # command: tail -f /dev/null
    environment:
      CONFIG_LOCATION: /app/configs/development_account/saas_development.yaml
      AWS_PROFILE: arn:aws:iam::759357822767:role/NoqSaasRoleLocalDev
      AWS_REGION: us-west-2
      AWS_DEFAULT_REGION: us-west-2
      STAGE: development
      PYTHONPATH: /app
      RUNTIME_PROFILE: PREFLIGHT
