# Use this traefik configuration when you want to run services on your localhost, and have traefik route to them without
# TLS

version: "3.8"

services:
  cloudumi_traefik:
    image: traefik
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./cloudumi_traefik/config_localhost_insecure:/etc/traefik/
    labels:
      - traefik.enable=false
volumes:
  certs:
