---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudumi-healthcheck
  labels:
    app: cloudumi-healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudumi-healthcheck
  template:
    metadata:
      labels:
        app: cloudumi-healthcheck
    spec:
      containers:
        - name: cloudumi-healthcheck
          image: cloudumi-healthcheck
          imagePullPolicy: Never

#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#    name: recommendations
#    labels:
#        app: recommendations
#spec:
#    replicas: 3
#    selector:
#        matchLabels:
#            app: recommendations
#    template:
#        metadata:
#            labels:
#                app: recommendations
#        spec:
#            containers:
#                - name: recommendations
#                  image: hidan/python-microservices-article-recommendations:0.1

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "cloudumi-healthcheck"
      port: 8090
  selector:
    app: cloudumi-healthcheck
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#    name: marketplace
#spec:
#    type: LoadBalancer
#    selector:
#        app: marketplace
#    ports:
#        - protocol: TCP
#          port: 9091
#          targetPort: 9091
