load("@cloudumi_python_ext//:requirements.bzl", "requirement")
load("//util/tests:defs.bzl", "pytest_test")

pytest_test(
    name = "test_identity",
    srcs = [
        "test_identity.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)
