filegroup(
    name = "configs",
    srcs = glob([
        "*.yaml",
    ]),
    visibility = ["//visibility:public"],
)

exports_files([
    "saas_development.yaml",
    "saas_development_container.yaml",
])