site_configs:
  stark_noq_dev:
    account_ids_to_name:
      "518317429440": jericho_missle_project
      "259868150464": jarvis
    policies:
      # the roles that SaaS consoleMe should assume to get to the central role in a client's account
      pre_role_arns_to_assume:
        - arn:aws:iam::259868150464:role/NoqClusterRole1
        - arn:aws:iam::518317429440:role/ConsoleMeCentralRole
      role_name: ConsoleMeSpokeRole
    security_logo:
      image: /images/logos/stark.png
    s3_cache_bucket: noqcache
    oidc_secrets:
      client_id: 0oaatebhlkuDajVAr4x6
      secret: A_SECRET
      client_scope:
        - email
        - groups
        - openid
    url: https://stark.noq.dev
    application_admin: bayareasec@gmail.com
    environment: dev
    development: true
    challenge_url:
      request_ip_must_match_challenge_creation_ip: true
    auth:
      get_user_by_password: false
      set_auth_cookie: true
      get_user_by_oidc: true
      force_redirect_to_identity_provider: false
    get_user_by_oidc_settings:
      resource: consoleme-oidc
      metadata_url: https://dev-876967.okta.com/oauth2/default/.well-known/oauth-authorization-server
      # If you have a metadata URL and it returns JSON with authorization_endpoint, token_endpoint, and jwks_uri, you do
      # not need to specify those values in the configuration.
      #authorization_endpoint: https://dev-123456.okta.com/oauth2/default/v1/authorize
      #token_endpoint: https://dev-123456.okta.com/oauth2/default/v1/token
      #jwks_uri: https://dev-123456.okta.com/oauth2/default/v1/keys
      jwt_verify: true
      jwt_email_key: email
      jwt_groups_key: groups
      grant_type: authorization_code
      id_token_response_key: id_token
      access_token_response_key: access_token
      access_token_audience: "consoleme"
    cloud_credential_authorization_mapping:
      role_tags:
        enabled: true
        authorized_groups_tags:
          - consoleme-authorized
        authorized_groups_cli_only_tags:
          - consoleme-owner-dl
          - consoleme-authorized-cli-only
    aws:
      issuer: YourCompany
      region: "us-east-1"
    celery:
      cache_resources_from_aws_config_across_accounts:
        enabled: false
    groups:
      can_edit_config:
        - configeditors@example.com
      can_admin_policies:
        - consoleme_admins@example.com
    jwt:
      email_key: email
    jwt_secret: usafasdfTp4`sSf-6E8\RAA
    support_contact: consoleme-support@example.com
    support_chat_url: https://www.example.com/slack/channel
    documentation_page: https://github.com/Netflix/consoleme/
