http:
  routers:
    frontend:
      entrypoints: web
      service: frontend
      rule: "PathPrefix(`/`)"
      priority: 1 # Lowest priority, last thing we will match
    api:
      entrypoints: web
      service: api
      rule: "PathPrefix(`/api`) || PathPrefix(`/saml`) || PathPrefix(`/auth`) || PathPrefix(`/noauth`)"

  services:
    api:
      loadbalancer:
        servers:
          - url: "http://api:8092/"
    frontend:
      loadbalancer:
        servers:
          - url: "http://frontend:8081/"
