http:
  routers:
    cloudumi_frontend:
      entrypoints: web
      service: cloudumi_frontend
      rule: "PathPrefix(`/`)"
      priority: 1 # Lowest priority, last thing we will match
    cloudumi_api:
      entrypoints: web
      service: cloudumi_api
      rule: "PathPrefix(`/api`) || PathPrefix(`/auth`) || PathPrefix(`/noauth`)"
    cloudumi_saml:
      entrypoints: web
      service: cloudumi_saml
      rule: "PathPrefix(`/saml`)"

  services:
    cloudumi_healthcheck:
      loadbalancer:
        servers:
          - url: "http://cloudumi_healthcheck:8090/"
    cloudumi_saml:
      loadbalancer:
        servers:
          - url: "http://cloudumi_saml:8091/"
    cloudumi_api:
      loadbalancer:
        servers:
          - url: "http://cloudumi_api:8092/"
    cloudumi_frontend:
      loadbalancer:
        servers:
          - url: "http://cloudumi_frontend:8081/"
