Resources:
  CloudUmiTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Join
          - '-'
          - - 'cloudumi-central-role'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
      Policies:
        -
          PolicyName: !Join
          - '-'
          - - 'cloudumi-central-acct-policy-ecs'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "access-analyzer:*"
                  - "cloudtrail:*"
                  - "cloudwatch:*"
                  - "config:SelectResourceConfig"
                  - "config:SelectAggregateResourceConfig"
                  - "dynamodb:batchgetitem"
                  - "dynamodb:batchwriteitem"
                  - "dynamodb:deleteitem"
                  - "dynamodb:describe*"
                  - "dynamodb:getitem"
                  - "dynamodb:getrecords"
                  - "dynamodb:getsharditerator"
                  - "dynamodb:putitem"
                  - "dynamodb:query"
                  - "dynamodb:scan"
                  - "dynamodb:updateitem"
                  - "dynamodb:CreateTable"
                  - "dynamodb:UpdateTimeToLive"
                  - "sns:createplatformapplication"
                  - "sns:createplatformendpoint"
                  - "sns:deleteendpoint"
                  - "sns:deleteplatformapplication"
                  - "sns:getendpointattributes"
                  - "sns:getplatformapplicationattributes"
                  - "sns:listendpointsbyplatformapplication"
                  - "sns:publish"
                  - "sns:setendpointattributes"
                  - "sns:setplatformapplicationattributes"
                  - "sts:assumerole"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "ses:sendmail"
                  - "ses:sendrawemail"
                Resource: "*"
              - Effect: Allow
                Action:
                  - "autoscaling:Describe*"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "config:BatchGet*"
                  - "config:List*"
                  - "config:Select*"
                  - "ec2:DescribeSubnets"
                  - "ec2:describevpcendpoints"
                  - "ec2:DescribeVpcs"
                  - "iam:GetAccountAuthorizationDetails"
                  - "iam:ListAccountAliases"
                  - "iam:ListAttachedRolePolicies"
                  - "ec2:describeregions"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketTagging"
                  - "s3:ListAllMyBuckets"
                  - "s3:ListBucket"
                  - "s3:PutBucketPolicy"
                  - "s3:PutBucketTagging"
                  - "sns:GetTopicAttributes"
                  - "sns:ListTagsForResource"
                  - "sns:ListTopics"
                  - "sns:SetTopicAttributes"
                  - "sns:TagResource"
                  - "sns:UnTagResource"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                  - "sqs:ListQueues"
                  - "sqs:ListQueueTags"
                  - "sqs:SetQueueAttributes"
                  - "sqs:TagQueue"
                  - "sqs:UntagQueue"
                Resource: "*"
  CloudUmiSnsCustomResource:
    Type: 'Custom::CloudUmiSnsCustomResource'
    Properties:
      Type: AWS_CT_CFG
      ServiceToken: arn:aws:sns:us-east-1:259868150464:noq_registration
      IntegrationName: !Ref 'AWS::StackName'
      ExternalId: !Ref ExternalIDParameter
      ActionType: "AWSCentralRegistration"
      Account: cloudumi
      TemplateVersion: 1.5
      AWSAccountId: !Ref 'AWS::AccountId'
Parameters:
  ExternalIDParameter:
    Type: String
    Default: __not_set__
    Description: Enter an external id associated with your account (contact NOQ for assistance if not automatically populated)