Resources:
  CloudUmiS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join
          - '-'
          - - 'cloudumi-bucket'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
  CloudUmiTaskRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Join
          - '-'
          - - 'cloudumi-task-role'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
      Policies:
        -
          PolicyName: !Join
          - '-'
          - - 'cloudumi-base-policy-ecs'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "access-analyzer:*"
                  - "autoscaling:Describe*"
                  - "cloudtrail:*"
                  - "cloudwatch:*"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "config:BatchGet*"
                  - "config:List*"
                  - "config:Select*"
                  - "config:SelectResourceConfig"
                  - "config:SelectAggregateResourceConfig"
                  - "dynamodb:batchgetitem"
                  - "dynamodb:batchwriteitem"
                  - "dynamodb:deleteitem"
                  - "dynamodb:describe*"
                  - "dynamodb:getitem"
                  - "dynamodb:getrecords"
                  - "dynamodb:getsharditerator"
                  - "dynamodb:putitem"
                  - "dynamodb:query"
                  - "dynamodb:scan"
                  - "dynamodb:updateitem"
                  - "ec2:DescribeSubnets"
                  - "ec2:describevpcendpoints"
                  - "ec2:describeregions"
                  - "ec2:DescribeVpcs"
                  - "iam:GetAccountAuthorizationDetails"
                  - "iam:ListAccountAliases"
                  - "iam:ListAttachedRolePolicies"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketTagging"
                  - "s3:ListAllMyBuckets"
                  - "s3:PutBucketPolicy"
                  - "s3:PutBucketTagging"
                  - "secretsmanager:GetResourcePolicy"
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecretVersionIds"
                  - "secretsmanager:ListSecrets"
                  - "ses:sendmail"
                  - "ses:sendrawemail"
                  - "sns:createplatformapplication"
                  - "sns:createplatformendpoint"
                  - "sns:deleteendpoint"
                  - "sns:deleteplatformapplication"
                  - "sns:getendpointattributes"
                  - "sns:getplatformapplicationattributes"
                  - "sns:GetTopicAttributes"
                  - "sns:listendpointsbyplatformapplication"
                  - "sns:ListTagsForResource"
                  - "sns:ListTopics"
                  - "sns:publish"
                  - "sns:setendpointattributes"
                  - "sns:setplatformapplicationattributes"
                  - "sns:SetTopicAttributes"
                  - "sns:TagResource"
                  - "sns:UnTagResource"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                  - "sqs:ListQueues"
                  - "sqs:ListQueueTags"
                  - "sqs:SetQueueAttributes"
                  - "sqs:TagQueue"
                  - "sqs:UntagQueue"
                  - "sts:assumerole"
                Resource: "*"
        -
          PolicyName: !Join
          - '-'
          - - 'cloudumi-policy-ecs-bucket-access'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - !GetAtt CloudUmiS3Bucket.Arn
                  - !Join
                    - ''
                    - - !GetAtt CloudUmiS3Bucket.Arn
                      - '/*'
  CloudUmiTrustRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !GetAtt CloudUmiTaskRole.Arn
            Action:
              - 'sts:AssumeRole'
      RoleName: !Join
          - '-'
          - - 'cloudumi-trust-role'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
      Policies:
        -
          PolicyName: !Join
          - '-'
          - - 'cloudumi-base-trust-policy-ecs'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "access-analyzer:*"
                  - "cloudtrail:*"
                  - "cloudwatch:*"
                  - "config:SelectResourceConfig"
                  - "config:SelectAggregateResourceConfig"
                  - "dynamodb:batchgetitem"
                  - "dynamodb:batchwriteitem"
                  - "dynamodb:deleteitem"
                  - "dynamodb:describe*"
                  - "dynamodb:getitem"
                  - "dynamodb:getrecords"
                  - "dynamodb:getsharditerator"
                  - "dynamodb:putitem"
                  - "dynamodb:query"
                  - "dynamodb:scan"
                  - "dynamodb:updateitem"
                  - "sns:createplatformapplication"
                  - "sns:createplatformendpoint"
                  - "sns:deleteendpoint"
                  - "sns:deleteplatformapplication"
                  - "sns:getendpointattributes"
                  - "sns:getplatformapplicationattributes"
                  - "sns:listendpointsbyplatformapplication"
                  - "sns:publish"
                  - "sns:setendpointattributes"
                  - "sns:setplatformapplicationattributes"
                  - "sts:assumerole"
                  - "autoscaling:Describe*"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "config:BatchGet*"
                  - "config:List*"
                  - "config:Select*"
                  - "ec2:DescribeSubnets"
                  - "ec2:describevpcendpoints"
                  - "ec2:DescribeVpcs"
                  - "iam:GetAccountAuthorizationDetails"
                  - "iam:ListAccountAliases"
                  - "iam:ListAttachedRolePolicies"
                  - "ec2:describeregions"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketTagging"
                  - "s3:ListAllMyBuckets"
                  - "s3:ListBucket"
                  - "s3:PutBucketPolicy"
                  - "s3:PutBucketTagging"
                  - "sns:GetTopicAttributes"
                  - "sns:ListTagsForResource"
                  - "sns:ListTopics"
                  - "sns:SetTopicAttributes"
                  - "sns:TagResource"
                  - "sns:UnTagResource"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                  - "sqs:ListQueues"
                  - "sqs:ListQueueTags"
                  - "sqs:SetQueueAttributes"
                  - "sqs:TagQueue"
                  - "sqs:UntagQueue"
                Resource: "*"
  CloudUmiTaskExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Join
          - '-'
          - - 'cloudumi-task-execution-role'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  CloudUmiCreateConfigurationFileLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Join
          - '-'
          - - 'cloudumi-create-configuration-file-lambda-role'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        -
          PolicyName: !Join
          - '-'
          - - 'cloudumi-create-configuration-file-lambda-role-bucket-access'
            - !Select
              - 0
              - !Split
                - '-'
                - !Select
                  - 2
                  - !Split
                    - '/'
                    - !Ref "AWS::StackId"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:PutObject"
                  - "s3:DeleteObject"
                Resource:
                  - !Join
                    - ''
                    - - !GetAtt CloudUmiS3Bucket.Arn
                      - '/*'
