load("@rules_python//python:defs.bzl", "py_library")
load("@rules_python//python:packaging.bzl", "py_wheel")
load("@cloudumi_python_ext//:requirements.bzl", "requirement")

filegroup(
    name = "src_files",
    srcs = (
        "__init__.py",
    ),
    visibility = ["//visibility:public"],
)

py_library(
    name = "lib",
    data = [],
    srcs_version = "PY3",
    srcs = [
        ":src_files",
    ],
    deps = [
        "//cloudumi_common/cloudumi_plugins/cloudumi_plugins/plugins/metrics:lib",
        requirement("boto3"),
        requirement("sentry_sdk"),
    ],
    visibility = ["//visibility:public"],
)
