load("@cloudumi_python_ext//:requirements.bzl", "requirement")
load("//util/tests:defs.bzl", "pytest_test")

pytest_test(
    name = "test_aws_iam_users",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_aws_iam_users.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_errors",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_errors.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_generate_changes",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_generate_changes.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_policies_handlers_v2",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_policies_handlers_v2.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_requests",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_requests.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_roles",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_roles.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_typeahead",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_typeahead.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_user_profile",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_user_profile.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)

pytest_test(
    name = "test_user",
    data = [
        "//util/tests:configs",
    ],
    srcs = [
        "test_user.py",
    ],
    deps = [
        "//util/tests:test_dependencies_lib",
    ],
)
