_global_:
  landing_page_domains:
    - shared.staging.noq.dev
  aws:
    node_role: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskRole
    stage: staging
    region: us-west-2
    attributes: 1
  deployment:
    domain_name: shared.staging.noq.dev
    namespace: shared
    zone: staging.noq.dev
    cluster_id: staging-noq-dev-shared-staging-1
  logging:
    file: ~/logs/cloudumi/cloudumi_tornado.log
  config:
    load_from_dynamo: true
    automatically_reload_configuration: true
    load_tenant_configurations_from_dynamo: true
  web:
    path: "/templates"
  s3_cache_bucket: cloudumi-cache.staging-noq-dev-shared-staging-1

  development: true
  environment: dev

  tornado:
    debug: false

    port: 8092
    xsrf: true
    xsrf_cookie_kwargs:
      samesite: strict
  plugins:
    auth: cmsaas_auth
    aws: cmsaas_aws
    group_mapping: cmsaas_group_mapping
    internal_celery_tasks: cmsaas_celery_tasks
    metrics: cmsaas_metrics
    internal_config: cmsaas_config
    internal_routes: cmsaas_internal_routes
    internal_policies: cmsaas_policies
  celery:
    clear_tasks_for_development: false
    purge: true
    broker:
      us-east-1: redis://staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com:6379/1
      us-west-2: redis://staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com:6379/1
      global: redis://staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com:6379/1
    backend:
      us-east-1: redis://staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com:6379/2
      us-west-2: redis://staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com:6379/2
      global: redis://staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com:6379/2
    debug: true
  # Saas Configuration
  redis:
    host:
      global: staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com
    port: 6379
    cluster_mode:
      enabled: false
      nodes:
        global:
          - host: staging-noq-dev-shared-staging-1-redis-service.eb1l6j.0001.usw2.cache.amazonaws.com
            port: 6379
  sentry:
    dsn: https://fb6ce9063023416592859491f2498fba@o1134078.ingest.sentry.io/6181191
