executionRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: []
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: staging-noq-dev-shared-staging-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: cluster-preflight
    entryPoint:
      - /bin/sh
      - "-c"
      - "python /app/common/preflight/run.py && (python api/__main__.py & echo $! > api_pid.txt) & (sleep 10; cd ui; cypress run; cypress_exit_code=$?; kill $(cat ../api_pid.txt); exit $cypress_exit_code)"
    linuxParameters:
      devices: []
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://staging-noq-dev-shared-staging-1-tenant-configuration-store/shared/staging.1.config.yaml
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: PREFLIGHT
      - name: STAGE
        value: staging
    dnsServers: []
    mountPoints:
      - containerPath: /data
        sourceVolume: efs-server-AP
    dockerSecurityOptions: []
    volumesFrom: []
    image: 259868150464.dkr.ecr.us-west-2.amazonaws.com/shared-staging-registry-api:latest
    essential: true
    links: []
    extraHosts: []
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: staging-noq-dev-shared-staging-1-preflight-tasks
placementConstraints: []
memory: "8192"
taskRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskRole
family: staging-noq-dev-shared-staging-1-preflight-tasks
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: "2048"
volumes:
  - name: efs-server-AP
    efsVolumeConfiguration:
      fileSystemId: fs-00d025e10faa53ff6
      transitEncryption: ENABLED
      authorizationConfig:
        accessPointId: fsap-05a781c2b23d8ef89
        iam: ENABLED
