executionRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: []
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: staging-noq-dev-shared-staging-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: celery-scheduler
    portMappings:
      - hostPort: 7071
        protocol: tcp
        containerPort: 7071

    entryPoint:
      - bash
      - -c
      - pip install argh watchdog; watchmedo auto-restart --recursive --pattern="api/*.py;common/*.py" --directory="." --ignore-patterns="./env/*" --verbose 'python /app/common/celery_tasks/run.py --profile CELERY_SCHEDULER & python /app/common/celery_tasks/run.py --profile CELERY_FLOWER & python /app/common/celery_tasks/run.py --profile CELERY_WORKER'

    linuxParameters:
      devices: []
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://staging-noq-dev-shared-staging-1-tenant-configuration-store/shared/staging.1.config.yaml
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: CELERY_SCHEDULER
      - name: STAGE
        value: staging
    dnsServers: []
    mountPoints:
      - containerPath: /data
        sourceVolume: efs-server-AP
    dockerSecurityOptions: []
    volumesFrom: []
    image: 259868150464.dkr.ecr.us-west-2.amazonaws.com/shared-staging-registry-api:latest
    essential: true
    links: []
    extraHosts: []
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: staging-noq-dev-shared-staging-1-celery-scheduler
placementConstraints: []
memory: "8192"
taskRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskRole
family: staging-noq-dev-shared-staging-1-celery-scheduler
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: "2048"
runtimePlatform:
  operatingSystemFamily: LINUX
  cpuArchitecture: X86_64
volumes:
  - name: efs-server-AP
    efsVolumeConfiguration:
      fileSystemId: fs-00d025e10faa53ff6
      transitEncryption: ENABLED
      authorizationConfig:
        accessPointId: fsap-05a781c2b23d8ef89
        iam: ENABLED
