executionRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: []
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: staging-noq-dev-shared-staging-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
    portMappings:
      - hostPort: 8092
        protocol: tcp
        containerPort: 8092
    linuxParameters:
      devices: []
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://staging-noq-dev-shared-staging-1-tenant-configuration-store/shared/staging.1.config.yaml
      - name: FRONTEND_SENTRY_DSN
        value: "https://5f3b026abb7649fe8b41e903dcb5820f@sentry.noq.dev:4443/2"
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: API
      - name: STAGE
        value: staging
      - name: PUBLIC_URL
        value: https://d2mxcvfujf7a5q.cloudfront.net/1.5.308/feat.en-128-new-request-ttl-attr/
    dnsServers: []
    mountPoints: []
    dockerSecurityOptions: []
    volumesFrom: []
    image: 259868150464.dkr.ecr.us-west-2.amazonaws.com/shared-staging-registry-api:staging
    essential: true
    links: []
    extraHosts: []
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: staging-noq-dev-shared-staging-1-api
placementConstraints: []
memory: "8192"
taskRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskRole
family: staging-noq-dev-shared-staging-1-api
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: "2048"
volumes: []
