executionRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: []
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: staging-noq-dev-shared-staging-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: celery-scheduler
    entryPoint:
      - /bin/sh
      - "-c"
      - "python /app/common/celery_tasks/run.py"
    linuxParameters:
      devices: []
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://staging-noq-dev-shared-staging-1-tenant-configuration-store/shared/staging.1.config.yaml
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: CELERY_SCHEDULER
      - name: STAGE
        value: staging
    dnsServers: []
    mountPoints: []
    dockerSecurityOptions: []
    volumesFrom: []
    image: 259868150464.dkr.ecr.us-west-2.amazonaws.com/shared-staging-registry-api:latest
    essential: true
    links: []
    extraHosts: []
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: staging-noq-dev-shared-staging-1-celery-scheduler
placementConstraints: []
memory: "2048"
taskRoleArn: arn:aws:iam::259868150464:role/staging-noq-dev-shared-staging-1-ecsTaskRole
family: staging-noq-dev-shared-staging-1-celery-scheduler
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: "1024"
volumes: []
