exports_files(
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)

exports_files(
    srcs = ["NoqLogo.png", "NoqLogo.svg"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "assets",
    srcs = glob(["**"]),
    visibility = ["//visibility:public"],
)