Resources:
  SpokeRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CentralAccountArnParameter
            Action:
              - "sts:AssumeRole"
              - "sts:TagSession"
      RoleName: !Ref SpokeRoleNameParameter
      Policies:
        - PolicyName: "spoke-acct-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "autoscaling:Describe*"
                  - "cloudwatch:Get*"
                  - "cloudwatch:List*"
                  - "config:BatchGet*"
                  - "config:List*"
                  - "config:Select*"
                  - "ec2:describeregions"
                  - "ec2:DescribeSubnets"
                  - "ec2:describevpcendpoints"
                  - "ec2:DescribeVpcs"
                  - "iam:*"
                  - "s3:GetBucketPolicy"
                  - "s3:GetBucketTagging"
                  - "s3:ListAllMyBuckets"
                  - "s3:ListBucket"
                  - "s3:PutBucketPolicy"
                  - "s3:PutBucketTagging"
                  - "sns:GetTopicAttributes"
                  - "sns:ListTagsForResource"
                  - "sns:ListTopics"
                  - "sns:SetTopicAttributes"
                  - "sns:TagResource"
                  - "sns:UnTagResource"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                  - "sqs:ListQueues"
                  - "sqs:ListQueueTags"
                  - "sqs:SetQueueAttributes"
                  - "sqs:TagQueue"
                  - "sqs:UntagQueue"
                Resource: "*"
  SnsCustomResource:
    Type: "Custom::SnsCustomResource"
    Properties:
      ServiceToken: !Ref RegistrationSnsQueArnParameter
      IntegrationName: !Ref "AWS::StackName"
      Host: !Ref HostParameter
      ActionType: "SpokeRegistration"
      TemplateVersion: 1.5
      AWSAccountId: !Ref "AWS::AccountId"
      CentralAccountArn: !Ref CentralAccountArnParameter
      SpokeRoleName: !Ref SpokeRoleNameParameter

Parameters:
  CentralAccountArnParameter:
    Description: >-
      The cross account role in customer's environment that will be allowed to assume this spoke role account.
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '^arn:aws:iam::\d{12}:role/.+'
    ConstraintDescription: 'Invalid CentralAccountArn value.  Must match pattern ^arn:aws:iam::\d{12}:role/.+'
  HostParameter:
    Description: >-
      The host parameter. Do not change this value!
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '[\w+_-]*'
    ConstraintDescription: 'Invalid Host value.  Must match pattern [\w+_-]*'
  SpokeRoleNameParameter:
    Description: >-
      The name of the spoke role in each customer account. Do not change this value!
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '[\w+_-]*'
    ConstraintDescription: 'Invalid SpokeRoleName value.  Must match pattern [\w+_-]*'
  RegistrationSnsQueArnParameter:
    Description: >-
      The SNS queue ARN that will be used to send registration messages to the SaaS
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '^arn:aws:sns:[\w-]*:\d{12}:.+'
    ConstraintDescription: 'Invalid RegistrationSnsQueArn value.  Must match pattern ^arn:aws:sns:[\w-]*:\d{12}:.+'
Outputs:
  CentralAccountArn:
    Description: The central role in the customer's environment that will be allowed to assume the created spoke role.
    Value: !Ref CentralAccountArnParameter
  Host:
    Description: Host to share with the SaaS provider for deployment
    Value: !Ref HostParameter
  SpokeRoleName:
    Description: The name of the spoke role in each customer account.
    Value: !Ref SpokeRoleNameParameter
  RegistrationSnsQueArn:
    Description: SNS Registration queue ARN
    Value: !Ref RegistrationSnsQueArnParameter
