Resources:
  SpokeRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref NOQCentralRoleArnParameter
            Action:
              - "sts:AssumeRole"
              - "sts:TagSession"
      RoleName: "NOQTerraformApplyRole"
      Policies:
        - PolicyName: "Permissions_Needed_For_TF_Apply"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                  - s3:ListObjects
                  - s3:GetObject
                  - dynamodb:GetItem
                  - ec2:DescribeAccountAttributes
                  - dynamodb:DescribeTable
                  - sqs:GetQueueAttributes
                  - ec2:DescribeVpcs
                  - iam:GetRole
                  - route53:ListHostedZones
                  - sts:GetCallerIdentity
                  - dynamodb:DescribeTable
                  - elasticache:DescribeCacheParameterGroups
                  - iam:GetRole
                  - dynamodb:DescribeTable
                  - ec2:DescribeVpcClassicLink
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - sqs:ListQueueTags
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - ec2:DescribeVpcClassicLinkDnsSupport
                  - sqs:GetQueueAttributes
                  - dynamodb:DescribeTimeToLive
                  - elasticache:DescribeCacheParameters
                  - dynamodb:ListTagsOfResource
                  - sqs:ListQueueTags
                  - dynamodb:ListTagsOfResource
                  - ec2:DescribeVpcAttribute
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeTable
                  - elasticache:ListTagsForResource
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeContinuousBackups
                  - ec2:DescribeVpcAttribute
                  - ec2:DescribeAddresses
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - dynamodb:DescribeTable
                  - ec2:DescribeNetworkAcls
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTable
                  - ec2:DescribeRouteTables
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - ec2:DescribeSecurityGroups
                  - route53:GetHostedZone
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - route53:ListTagsForResource
                  - iam:ListRolePolicies
                  - iam:ListRolePolicies
                  - iam:GetRolePolicy
                  - iam:GetRolePolicy
                  - dynamodb:DescribeTimeToLive
                  - sns:GetTopicAttributes
                  - dynamodb:DescribeTimeToLive
                  - iam:ListAttachedRolePolicies
                  - iam:ListAttachedRolePolicies
                  - s3:HeadBucket
                  - dynamodb:DescribeTable
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketPolicy
                  - s3:GetBucketAcl
                  - dynamodb:DescribeTimeToLive
                  - sns:ListTagsForResource
                  - dax:DescribeParameterGroups
                  - s3:GetBucketCors
                  - s3:GetBucketWebsite
                  - s3:GetBucketVersioning
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketAccelerateConfiguration
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketLogging
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketLifecycleConfiguration
                  - s3:GetBucketReplication
                  - s3:GetBucketEncryption
                  - s3:GetObjectLockConfiguration
                  - dax:DescribeParameters
                  - s3:HeadBucket
                  - s3:GetBucketTagging
                  - ecr:DescribeRepositories
                  - email:GetIdentityVerificationAttributes
                  - ecr:ListTagsForResource
                  - ecr:DescribeRepositories
                  - ecr:DescribeRepositories
                  - ecr:ListTagsForResource
                  - ecr:ListTagsForResource
                  - acm:DescribeCertificate
                  - dynamodb:DescribeTimeToLive
                  - secretsmanager:GetSecretValue
                  - dynamodb:DescribeTable
                  - acm:ListTagsForCertificate
                  - dynamodb:DescribeContinuousBackups
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - ec2:DescribeSubnets
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeSecurityGroups
                  - dynamodb:DescribeTimeToLive
                  - elasticloadbalancing:DescribeTargetGroups
                  - dynamodb:ListTagsOfResource
                  - ec2:DescribeSecurityGroups
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - ec2:DescribeSecurityGroups
                  - elasticloadbalancing:DescribeTags
                  - ec2:DescribeSubnets
                  - ec2:DescribeSubnets
                  - ec2:DescribeSubnets
                  - sns:GetSubscriptionAttributes
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueAttributes
                  - sns:GetSubscriptionAttributes
                  - s3:HeadBucket
                  - email:GetIdentityMailFromDomainAttributes
                  - s3:HeadBucket
                  - s3:GetBucketPolicy
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketAcl
                  - s3:GetBucketPolicy
                  - s3:GetBucketAcl
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketCors
                  - s3:GetBucketWebsite
                  - s3:GetBucketVersioning
                  - s3:GetBucketAccelerateConfiguration
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketLogging
                  - s3:GetBucketRequestPayment
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketLifecycleConfiguration
                  - s3:GetBucketCors
                  - s3:GetBucketReplication
                  - s3:GetBucketWebsite
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketEncryption
                  - s3:GetBucketVersioning
                  - s3:GetObjectLockConfiguration
                  - dynamodb:DescribeTimeToLive
                  - s3:GetBucketAccelerateConfiguration
                  - s3:HeadBucket
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketTagging
                  - s3:GetBucketLogging
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketLifecycleConfiguration
                  - route53:GetHostedZone
                  - s3:GetBucketReplication
                  - s3:GetBucketEncryption
                  - s3:GetObjectLockConfiguration
                  - s3:HeadBucket
                  - s3:GetBucketTagging
                  - autoscaling:DescribeScalableTargets
                  - dynamodb:DescribeTimeToLive
                  - autoscaling:DescribeScalableTargets
                  - route53:ListResourceRecordSets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - kms:DescribeKey
                  - ec2:DescribeRouteTables
                  - kms:GetKeyPolicy
                  - kms:GetKeyRotationStatus
                  - kms:ListResourceTags
                  - ec2:DescribeNatGateways
                  - sns:GetTopicAttributes
                  - s3:GetPublicAccessBlock
                  - s3:GetPublicAccessBlock
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - autoscaling:DescribeScalingPolicies
                  - acm:DescribeCertificate
                  - ec2:DescribeSecurityGroups
                  - kms:ListAliases
                  - logs:DescribeLogGroups
                  - dynamodb:DescribeTimeToLive
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetResourcePolicy
                  - ec2:DescribeRouteTables
                  - ec2:DescribeRouteTables
                  - ec2:DescribeRouteTables
                  - secretsmanager:GetSecretValue
                  - ec2:DescribeSecurityGroups
                  - dax:DescribeSubnetGroups
                  - elasticache:DescribeCacheSubnetGroups
                  - elasticache:ListTagsForResource
                  - ec2:DescribeRouteTables
                  - ec2:DescribeRouteTables
                  - iam:GetRole
                  - logs:ListTagsLogGroup
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeTags
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - iam:ListRolePolicies
                  - dax:DescribeClusters
                  - elasticache:DescribeReplicationGroups
                  - dynamodb:DescribeTimeToLive
                  - dax:ListTags
                  - iam:GetRolePolicy
                  - elasticache:DescribeCacheClusters
                  - iam:ListAttachedRolePolicies
                  - elasticache:ListTagsForResource
                  - ecs:DescribeClusters
                  - elasticloadbalancing:DescribeListeners
                  - dynamodb:DescribeTimeToLive
                  - elasticloadbalancing:DescribeTags
                  - elasticloadbalancing:DescribeListeners
                  - autoscaling:DescribeScalableTargets
                  - elasticloadbalancing:DescribeTags
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - elasticache:DescribeReplicationGroups
                  - elasticache:ListTagsForResource
                  - elasticache:DescribeCacheClusters
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - autoscaling:DescribeScalingPolicies
                  - dynamodb:DescribeTimeToLive
                  - dynamodb:ListTagsOfResource
                  - autoscaling:DescribeScalableTargets
                  - autoscaling:DescribeScalingPolicies
                  - ec2:DescribeAccountAttributes
                  - route53:GetHostedZone
                  - route53:GetHostedZone
                  - ec2:DescribeRouteTables
                  - route53:ChangeResourceRecordSets
                  - route53:ListResourceRecordSets
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:GetChange
                  - route53:GetChange
                  - route53:GetHostedZone
                  - route53:GetChange
                  - route53:ListResourceRecordSets
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                  - acm:RequestCertificate
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - acm:ListTagsForCertificate
                  - route53:GetHostedZone
                  - route53:ChangeResourceRecordSets
                  - route53:GetChange
                  - route53:GetChange
                  - route53:GetHostedZone
                  - route53:ListResourceRecordSets
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - acm:DescribeCertificate
                  - elasticloadbalancing:ModifyListener
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:DescribeTags
                  - acm:DeleteCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificate
                  - acm:DeleteCertificate
                  - s3:PutObject
                  - dynamodb:PutItem
                Resource: "*"

Parameters:
  NOQCentralRoleArnParameter:
    Description: The role used by NOQ to assume this role, to be created, and deploy the NOQ infrastructure using Terraform
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: ^arn:aws:iam::\d{12}:role/.+
    ConstraintDescription: Invalid CentralRoleArn value.  Must match pattern ^arn:aws:iam::\d{12}:role/.+ with a length between 2-100

Outputs:
  NOQTerraformApplyRole:
    Description: The role that NOQ will use to setup the infrastructure in the environment
    Value: !Ref NOQTerraformApplyRole
