Resources:
  SpokeRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref CentralRoleArnParameter
            Action:
              - "sts:AssumeRole"
              - "sts:TagSession"
      RoleName: !Ref SpokeRoleNameParameter
      Policies:
        - PolicyName: "spoke-acct-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  Fn::If:
                    - ReadOnlyModeEnabled
                    - - "config:BatchGet*"
                      - "config:GetResourceConfigHistory"
                      - "config:List*"
                      - "config:Select*"
                      - "ec2:describeregions"
                      - "iam:GenerateCredentialReport"
                      - "iam:GenerateOrganizationsAccessReport"
                      - "iam:GenerateServiceLastAccessedDetails"
                      - "iam:GetAccessKeyLastUsed"
                      - "iam:GetAccountAuthorizationDetails"
                      - "iam:GetAccountSummary"
                      - "iam:GetCredentialReport"
                      - "iam:GetGroup"
                      - "iam:GetGroupPolicy"
                      - "iam:GetInstanceProfile"
                      - "iam:GetPolicy"
                      - "iam:GetPolicyVersion"
                      - "iam:GetRole"
                      - "iam:GetRolePolicy"
                      - "iam:GetServiceLastAccessedDetails"
                      - "iam:GetServiceLastAccessedDetailsWithEntities"
                      - "iam:GetUser"
                      - "iam:GetUserPolicy"
                      - "iam:ListAccessKeys"
                      - "iam:ListAccountAliases"
                      - "iam:ListAttachedRolePolicies"
                      - "iam:ListAttachedUserPolicies"
                      - "iam:ListEntitiesForPolicy"
                      - "iam:ListGroupPolicies"
                      - "iam:ListGroups"
                      - "iam:ListGroupsForUser"
                      - "iam:ListInstanceProfileTags"
                      - "iam:ListInstanceProfiles"
                      - "iam:ListInstanceProfilesForRole"
                      - "iam:ListPolicies"
                      - "iam:ListPolicyTags"
                      - "iam:ListPolicyVersions"
                      - "iam:ListRolePolicies"
                      - "iam:ListRoleTags"
                      - "iam:ListRoles"
                      - "iam:ListUserPolicies"
                      - "iam:ListUserTags"
                      - "iam:ListUsers"
                      - "iam:SimulateCustomPolicy"
                      - "iam:SimulatePrincipalPolicy"
                      - "organizations:DescribeAccount"
                      - "organizations:DescribeEffectivePolicy"
                      - "organizations:DescribeOrganization"
                      - "organizations:DescribeOrganizationalUnit"
                      - "organizations:DescribePolicy"
                      - "organizations:ListAccounts"
                      - "organizations:ListAccountsForParent"
                      - "organizations:ListChildren"
                      - "organizations:ListCreateAccountStatus"
                      - "organizations:ListDelegatedAdministrators"
                      - "organizations:ListDelegatedServicesForAccount"
                      - "organizations:ListHandshakesForAccount"
                      - "organizations:ListHandshakesForOrganization"
                      - "organizations:ListOrganizationalUnitsForParent"
                      - "organizations:ListParents"
                      - "organizations:ListPolicies"
                      - "organizations:ListPoliciesForTarget"
                      - "organizations:ListRoots"
                      - "organizations:ListTagsForResource"
                      - "organizations:ListTargetsForPolicy"
                      - "s3:GetBucketPolicy"
                      - "s3:GetBucketTagging"
                      - "s3:ListAllMyBuckets"
                      - "s3:ListBucket"
                      - "sns:GetTopicAttributes"
                      - "sns:ListTagsForResource"
                      - "sns:ListTopics"
                      - "sqs:GetQueueAttributes"
                      - "sqs:GetQueueUrl"
                      - "sqs:ListQueueTags"
                      - "sqs:ListQueues"
                    - - "config:BatchGet*"
                      - "config:GetResourceConfigHistory"
                      - "config:List*"
                      - "config:Select*"
                      - "ec2:describeregions"
                      - "iam:AddRoleToInstanceProfile"
                      - "iam:AttachRolePolicy"
                      - "iam:AttachUserPolicy"
                      - "iam:CreateInstanceProfile"
                      - "iam:CreateRole"
                      - "iam:DeleteAccessKey"
                      - "iam:DeleteInstanceProfile"
                      - "iam:DeletePolicy"
                      - "iam:DeletePolicyVersion"
                      - "iam:DeleteRole"
                      - "iam:DeleteRolePermissionsBoundary"
                      - "iam:DeleteRolePolicy"
                      - "iam:DeleteUser"
                      - "iam:DeleteUserPermissionsBoundary"
                      - "iam:DeleteUserPolicy"
                      - "iam:DeleteVirtualMFADevice"
                      - "iam:DetachRolePolicy"
                      - "iam:DetachUserPolicy"
                      - "iam:GenerateCredentialReport"
                      - "iam:GenerateOrganizationsAccessReport"
                      - "iam:GenerateServiceLastAccessedDetails"
                      - "iam:GetAccessKeyLastUsed"
                      - "iam:GetAccountAuthorizationDetails"
                      - "iam:GetAccountSummary"
                      - "iam:GetCredentialReport"
                      - "iam:GetGroup"
                      - "iam:GetGroupPolicy"
                      - "iam:GetInstanceProfile"
                      - "iam:GetPolicy"
                      - "iam:GetPolicyVersion"
                      - "iam:GetRole"
                      - "iam:GetRolePolicy"
                      - "iam:GetServiceLastAccessedDetails"
                      - "iam:GetServiceLastAccessedDetailsWithEntities"
                      - "iam:GetUser"
                      - "iam:GetUserPolicy"
                      - "iam:ListAccessKeys"
                      - "iam:ListAccountAliases"
                      - "iam:ListAttachedRolePolicies"
                      - "iam:ListAttachedUserPolicies"
                      - "iam:ListEntitiesForPolicy"
                      - "iam:ListGroupPolicies"
                      - "iam:ListGroups"
                      - "iam:ListGroupsForUser"
                      - "iam:ListInstanceProfileTags"
                      - "iam:ListInstanceProfiles"
                      - "iam:ListInstanceProfilesForRole"
                      - "iam:ListPolicies"
                      - "iam:ListPolicyTags"
                      - "iam:ListPolicyVersions"
                      - "iam:ListRolePolicies"
                      - "iam:ListRoleTags"
                      - "iam:ListRoles"
                      - "iam:ListUserPolicies"
                      - "iam:ListUserTags"
                      - "iam:ListUsers"
                      - "iam:PassRole"
                      - "iam:PutRolePermissionsBoundary"
                      - "iam:PutRolePolicy"
                      - "iam:PutUserPermissionsBoundary"
                      - "iam:PutUserPolicy"
                      - "iam:RemoveRoleFromInstanceProfile"
                      - "iam:RemoveUserFromGroup"
                      - "iam:SetDefaultPolicyVersion"
                      - "iam:SimulateCustomPolicy"
                      - "iam:SimulatePrincipalPolicy"
                      - "iam:TagInstanceProfile"
                      - "iam:TagPolicy"
                      - "iam:TagRole"
                      - "iam:TagUser"
                      - "iam:UntagInstanceProfile"
                      - "iam:UntagPolicy"
                      - "iam:UntagRole"
                      - "iam:UntagUser"
                      - "iam:UpdateAssumeRolePolicy"
                      - "iam:UpdateRole"
                      - "iam:UpdateRoleDescription"
                      - "iam:UpdateUser"
                      - "organizations:DescribeAccount"
                      - "organizations:DescribeEffectivePolicy"
                      - "organizations:DescribeOrganization"
                      - "organizations:DescribeOrganizationalUnit"
                      - "organizations:DescribePolicy"
                      - "organizations:ListAccounts"
                      - "organizations:ListAccountsForParent"
                      - "organizations:ListChildren"
                      - "organizations:ListCreateAccountStatus"
                      - "organizations:ListDelegatedAdministrators"
                      - "organizations:ListDelegatedServicesForAccount"
                      - "organizations:ListHandshakesForAccount"
                      - "organizations:ListHandshakesForOrganization"
                      - "organizations:ListOrganizationalUnitsForParent"
                      - "organizations:ListParents"
                      - "organizations:ListPolicies"
                      - "organizations:ListPoliciesForTarget"
                      - "organizations:ListRoots"
                      - "organizations:ListTagsForResource"
                      - "organizations:ListTargetsForPolicy"
                      - "organizations:TagResource"
                      - "organizations:UntagResource"
                      - "s3:GetBucketPolicy"
                      - "s3:GetBucketTagging"
                      - "s3:ListAllMyBuckets"
                      - "s3:ListBucket"
                      - "s3:PutBucketPolicy"
                      - "s3:PutBucketTagging"
                      - "sns:GetTopicAttributes"
                      - "sns:ListTagsForResource"
                      - "sns:ListTopics"
                      - "sns:SetTopicAttributes"
                      - "sns:TagResource"
                      - "sns:UnTagResource"
                      - "sqs:GetQueueAttributes"
                      - "sqs:GetQueueUrl"
                      - "sqs:ListQueueTags"
                      - "sqs:ListQueues"
                      - "sqs:SetQueueAttributes"
                      - "sqs:TagQueue"
                      - "sqs:UntagQueue"
                Resource: "*"
  SnsCustomResource:
    Type: "Custom::SnsCustomResource"
    DependsOn: "SpokeRole"
    Properties:
      ServiceToken: !Ref RegistrationTopicArnParameter
      IntegrationName: !Ref "AWS::StackName"
      Host: !Ref HostParameter
      ActionType: "AWSSpokeAcctRegistration"
      TemplateVersion: 1.5
      AWSAccountId: !Ref "AWS::AccountId"
      CentralRoleArn: !Ref CentralRoleArnParameter
      SpokeRoleName: !Ref SpokeRoleNameParameter
      ExternalId: !Ref ExternalIDParameter
      AccountName: !Ref AccountNameParameter
      ReadOnlyMode: !Ref ReadOnlyModeParameter

Conditions:
  ReadOnlyModeEnabled: !Equals [true, !Ref ReadOnlyModeParameter]

Parameters:
  AccountNameParameter:
    Description: Name to identify the account by.
    Type: String
    MinLength: "0"
    MaxLength: "50"
    AllowedPattern: '[\s\S]*'
    ConstraintDescription: Invalid account name value.  Must match pattern [\s\S]* with a length between 1-50. Defaults to account id
  ExternalIDParameter:
    Description: ExternalId is used for verification. Do not change this value!
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '[\w+=,.@:\/-]*'
    ConstraintDescription: Invalid ExternalID value.  Must match pattern [\w+=,.@:\/-]* with a length between 2-100
  HostParameter:
    Description: The host parameter. Do not change this value!
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '[\w+_-]*'
    ConstraintDescription: Invalid Host value.  Must match pattern [\w+_-]* with a length between 2-100
  SpokeRoleNameParameter:
    Description: The name of the spoke role in each customer account. Do not change this value!
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: '[\w+_-]*'
    ConstraintDescription: Invalid SpokeRoleName value.  Must match pattern [\w+_-]* with a length between 2-100
  RegistrationTopicArnParameter:
    Description: The SNS queue ARN that will be used to send registration messages to the SaaS. Do not change this value!
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: ^arn:aws:sns:[\w-]*:\d{12}:.+
    ConstraintDescription: Invalid RegistrationTopicArn value.  Must match pattern ^arn:aws:sns:[\w-]*:\d{12}:.+ with a length between 2-100
  ReadOnlyModeParameter:
    Description: Only give read-only permissions to the Spoke role.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  CentralRoleArnParameter:
    Description: The cross account role in customer's environment that will be allowed to assume this spoke role account.
    Type: String
    MinLength: "2"
    MaxLength: "100"
    AllowedPattern: ^arn:aws:iam::\d{12}:role/.+
    ConstraintDescription: Invalid CentralRoleArn value.  Must match pattern ^arn:aws:iam::\d{12}:role/.+ with a length between 2-100

Outputs:
  CentralRoleArn:
    Description: The central role in the customer's environment that will be allowed to assume the created spoke role.
    Value: !Ref CentralRoleArnParameter
  ExternalID:
    Description: ExternalID to share with the SaaS for verification
    Value: !Ref ExternalIDParameter
  AccountName:
    Description: Name to identify the account by. Defaults to the account id.
    Value: !Ref AccountNameParameter
  Host:
    Description: Host to share with the SaaS provider for deployment
    Value: !Ref HostParameter
  SpokeRoleName:
    Description: The name of the spoke role in each customer account.
    Value: !Ref SpokeRoleNameParameter
  RegistrationTopicArnParameter:
    Description: SNS Registration queue ARN
    Value: !Ref RegistrationTopicArnParameter
  ReadOnly:
    Description: Does NOQ only have read access to the account
    Value: !Ref ReadOnlyModeParameter
