version: "3"
services:
  cloudumi_create_dev_resources:
    volumes:
      - ~/.aws:/root/.aws:cached
      - ./cloudumi_api:/apps/cloudumi_api:cached
      - ./cloudumi_config:/apps/cloudumi_config:cached
      - ./cloudumi_common:/apps/cloudumi_common:cached
    command: bash -c '
      python /apps/cloudumi_common/cloudumi_common/scripts/generate_random_resources_localstack.py'
    build:
      context: .
      dockerfile: cloudumi_api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONASYNCIODEBUG=1
