# docker-compose -f deploy/docker-compose-dependencies.yaml -f docker-compose-bazel-api.yaml up -d
version: "3"
services:
  api:
    build:
      context: ../
    volumes:
      - ~/.aws:/root/.aws:cached
      - ../configs:/app/configs:cached
    #    command: tail -f /dev/null
    # command: "python api/debug.py"
    command: bash -c 'pip install debugpy && python -m debugpy --listen 0.0.0.0:9092 api/__main__.py'
    depends_on:
      - redis-cluster
      - cloudumi-dynamodb
    links:
      - redis-cluster
      - cloudumi-dynamodb
    environment:
      AWS_PROFILE: noq_dev
      CONFIG_LOCATION: /app/configs/development_account/saas_development.yaml
      # FAULTHANDLER_ENABLED: "true"
    ports:
      - 8092:8092
      - 9092:9092
