# Use this traefik configuration when you want to run services in containers, and have traefik route http://localhost
# to those containers insecurely

version: "3"

services:
  cloudumi_traefik:
    image: traefik
    ports:
      - "80:80"
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/letsencrypt
      - ./traefik/config_docker_insecure:/etc/traefik/
    labels:
      - traefik.enable=false

volumes:
  certs:
