# docker-compose -f deploy/docker-compose-dependencies.yaml -f docker-compose-bazel-api.yaml up -d
version: "3"
services:
  api:
    build:
      context: ../
    volumes:
      - ~/.aws:/root/.aws:cached
    #    command: tail -f /dev/null
    depends_on:
      - redis-cluster
      - cloudumi-dynamodb
    links:
      - redis-cluster
      - cloudumi-dynamodb
    environment:
      AWS_PROFILE: noq_dev
  frontend:
    build:
      context: ../frontend
