# docker-compose -f deploy/docker-compose-dependencies.yaml -f docker-compose-bazel-api.yaml up -d
version: "3"
services:
  api:
    image: bazel/api:container-dev-local
    volumes:
      - ~/.aws:/root/.aws:cached
    depends_on:
      - redis-cluster
      - cloudumi-dynamodb
    links:
      - redis-cluster
      - cloudumi-dynamodb
    ports:
      - 8092:8092
