# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import identity_service_pb2 as identity__service__pb2


class GroupManagementServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GroupManagement = channel.unary_unary(
            "/GroupManagementService/GroupManagement",
            request_serializer=identity__service__pb2.GroupRequest.SerializeToString,
            response_deserializer=identity__service__pb2.GroupResponse.FromString,
        )


class GroupManagementServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GroupManagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GroupManagementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GroupManagement": grpc.unary_unary_rpc_method_handler(
            servicer.GroupManagement,
            request_deserializer=identity__service__pb2.GroupRequest.FromString,
            response_serializer=identity__service__pb2.GroupResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "GroupManagementService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class GroupManagementService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GroupManagement(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/GroupManagementService/GroupManagement",
            identity__service__pb2.GroupRequest.SerializeToString,
            identity__service__pb2.GroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
