import { IRequest } from './types';

export enum SELF_SERVICE_STEPS {
  SELECT_PROVIDER,
  REQUEST_TYPE,
  EXPRESS_CHANGE_TYPES,
  EXPRESS_CHANGE_DETAILS,
  SELECT_IDENTITY,
  CHANGE_TYPE,
  REQUEST_PREVIEW
}

export enum REQUEST_FLOW_MODE {
  ADVANCED_MODE = 'ADVANCED_MODE',
  EXPRESS_MODE = 'EXPRESS_MODE'
}

export const ADVANCED_MODE_NEXT_STEP_MAP = {
  [SELF_SERVICE_STEPS.SELECT_PROVIDER]: SELF_SERVICE_STEPS.REQUEST_TYPE,
  [SELF_SERVICE_STEPS.REQUEST_TYPE]: SELF_SERVICE_STEPS.SELECT_IDENTITY,
  [SELF_SERVICE_STEPS.SELECT_IDENTITY]: SELF_SERVICE_STEPS.CHANGE_TYPE,
  [SELF_SERVICE_STEPS.CHANGE_TYPE]: SELF_SERVICE_STEPS.REQUEST_PREVIEW
};

export const EXPRESS_MODE_NEXT_STEP_MAP = {
  [SELF_SERVICE_STEPS.SELECT_PROVIDER]: SELF_SERVICE_STEPS.REQUEST_TYPE,
  [SELF_SERVICE_STEPS.REQUEST_TYPE]: SELF_SERVICE_STEPS.EXPRESS_CHANGE_TYPES,
  [SELF_SERVICE_STEPS.EXPRESS_CHANGE_TYPES]:
    SELF_SERVICE_STEPS.EXPRESS_CHANGE_DETAILS,
  [SELF_SERVICE_STEPS.EXPRESS_CHANGE_DETAILS]:
    SELF_SERVICE_STEPS.REQUEST_PREVIEW
};

export const ADVANCED_MODE_PREVIOUS_STEP_MAP = {
  [SELF_SERVICE_STEPS.REQUEST_TYPE]: SELF_SERVICE_STEPS.SELECT_PROVIDER,
  [SELF_SERVICE_STEPS.SELECT_IDENTITY]: SELF_SERVICE_STEPS.REQUEST_TYPE,
  [SELF_SERVICE_STEPS.CHANGE_TYPE]: SELF_SERVICE_STEPS.SELECT_IDENTITY,
  [SELF_SERVICE_STEPS.REQUEST_PREVIEW]: SELF_SERVICE_STEPS.CHANGE_TYPE
};

export const EXPRESS_MODE_PREVIOUS_STEP_MAP = {
  [SELF_SERVICE_STEPS.REQUEST_TYPE]: SELF_SERVICE_STEPS.SELECT_PROVIDER,
  [SELF_SERVICE_STEPS.EXPRESS_CHANGE_TYPES]: SELF_SERVICE_STEPS.REQUEST_TYPE,
  [SELF_SERVICE_STEPS.EXPRESS_CHANGE_DETAILS]:
    SELF_SERVICE_STEPS.EXPRESS_CHANGE_TYPES,
  [SELF_SERVICE_STEPS.REQUEST_PREVIEW]:
    SELF_SERVICE_STEPS.EXPRESS_CHANGE_DETAILS
};

export const DEFAULT_REQUEST: IRequest = {
  provider: '',
  requestType: null,
  changeType: null,
  identityType: null,
  identity: null,
  expirationDate: '',
  justification: '',
  express_template_id: '',
  requestedChanges: []
};

export enum EXPIRATION_TYPE {
  RELATIVE = 'RELATIVE',
  ABSOLUTE = 'ABSOLUTE',
  NEVER = 'NEVER'
}
