executionRoleArn: arn:aws:iam::775726381634:role/cyberdyne-noq-dev-cyberdyne-prod-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: []
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: cyberdyne-noq-dev-cyberdyne-prod-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: celery-worker
    entryPoint:
      - /bin/sh
      - "-c"
      - "python /app/common/celery_tasks/run.py"
    linuxParameters:
      devices: []
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://cyberdyne-noq-dev-cyberdyne-prod-1-tenant-configuration-store/cyberdyne/prod.1.config.yaml
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: CELERY_WORKER
      - name: STAGE
        value: prod
    dnsServers: []
    mountPoints:
      - containerPath: /data
        sourceVolume: efs-server-AP
    dockerSecurityOptions: []
    volumesFrom: []
    image: 775726381634.dkr.ecr.us-west-2.amazonaws.com/cyberdyne-prod-registry-api:prod
    essential: true
    links: []
    extraHosts: []
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: cyberdyne-noq-dev-cyberdyne-prod-1-celery-worker
placementConstraints: []
memory: "8192"
taskRoleArn: arn:aws:iam::775726381634:role/cyberdyne-noq-dev-cyberdyne-prod-1-ecsTaskRole
family: cyberdyne-noq-dev-cyberdyne-prod-1-celery-worker
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: "2048"
volumes:
  - name: efs-server-AP
    efsVolumeConfiguration:
      fileSystemId: fs-04a43ab62edb748e9
      transitEncryption: ENABLED
      authorizationConfig:
        accessPointId: fsap-0f1d0dd184aee42a9
        iam: ENABLED
