executionRoleArn: arn:aws:iam::775726381634:role/cyberdyne-noq-dev-cyberdyne-prod-1-ecsTaskExecutionRole
containerDefinitions:
  - dnsSearchDomains: [ ]
    logConfiguration:
      logDriver: awslogs
      options:
        awslogs-group: cyberdyne-noq-dev-cyberdyne-prod-1
        awslogs-region: us-west-2
        awslogs-stream-prefix: celery-flower
    portMappings:
      - hostPort: 7071
        protocol: tcp
        containerPort: 7071
    linuxParameters:
      devices: [ ]
      initProcessEnabled: true
    cpu: 0
    environment:
      - name: CONFIG_LOCATION
        value: s3://cyberdyne-noq-dev-cyberdyne-prod-1-tenant-configuration-store/cyberdyne/prod.1.config.yaml
      - name: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
      - name: RUNTIME_PROFILE
        value: CELERY_FLOWER
      - name: STAGE
        value: prod
    dnsServers: [ ]
    mountPoints: [ ]
    dockerSecurityOptions: [ ]
    volumesFrom: [ ]
    image: 775726381634.dkr.ecr.us-west-2.amazonaws.com/cyberdyne-prod-registry-celery:prod
    essential: true
    links: [ ]
    extraHosts: [ ]
    pseudoTerminal: false
    readonlyRootFilesystem: false
    privileged: false
    name: cyberdyne-noq-dev-cyberdyne-prod-1-celery-flower
placementConstraints: [ ]
memory: '512'
taskRoleArn: arn:aws:iam::775726381634:role/cyberdyne-noq-dev-cyberdyne-prod-1-ecsTaskRole
family: cyberdyne-noq-dev-cyberdyne-prod-1-celery-flower
requiresCompatibilities:
  - FARGATE
networkMode: awsvpc
cpu: '256'
volumes: [ ]