export enum ChallengeName {
  NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED',
  SOFTWARE_TOKEN_MFA = 'SOFTWARE_TOKEN_MFA'
}

export enum AuthenticationFlowType {
  USER_SRP_AUTH = 'USER_SRP_AUTH',
  CUSTOM_AUTH = 'CUSTOM_AUTH',
  USER_PASSWORD_AUTH = 'USER_PASSWORD_AUTH'
}
