api:
  insecure: true
providers:
  file:
    filename: /etc/traefik/dynamic_conf.yaml

accesslog:
  filepath: /var/log/traefik/access.log
  bufferingsize: 100
#
#certificatesresolvers:
#  letsencrypt:
#    acme:
#      dnschallenge: true
#      provider: cloudflare
#      email: ccastrapel@gmail.com
#      storage: /letsencrypt/acme.json

entryPoints:
  web:
    address: ":80"
#    http:
#      domains:
#        - main: cloudumi.com
#          sans: "*.cloudumi.com"
#  websecure:
#    address: "443"
#    http:
#      tls:
#        certResolver: letsencrypt
#      domains:
#        - main: cloudumi.com
#          sans: "*.cloudumi.com"
