filegroup(
    name = "src",
    srcs = glob([
        "assets/**/*",
        "auth/**/*",
        "components/**/*",
        "helpers/**/*",
        "semantic-ui/**/*",
        "*.js",
        "*.css",
        "*.svg",
    ]),
    visibility = ["//visibility:public"],
)

exports_files([
    "index.js",
])