site_configs:
  cognito_noq_localhost:
    policies:
      # the roles that SaaS consoleMe should assume to get to the central role in a client's account
      pre_role_arns_to_assume:
        - arn:aws:iam::259868150464:role/NoqClusterRole1
        - arn:aws:iam::259868150464:role/ConsoleMeCentralRole
      role_name: ConsoleMeSpokeRole
    consoleme_s3_bucket: consolemecache
    secrets:
      auth:
        oidc:
          client_id: 1fpq9om50b4bm1225o8it875jj
          client_secret: 455amdhl2nfnnqpnrtar4eh2iigbl31entnti7i3mffbi7rs9va
    url: https://cognito.noq.localhost
    application_admin: bayareasec@gmail.com
    environment: dev
    development: true
    challenge_url:
      request_ip_must_match_challenge_creation_ip: true
    auth:
      get_user_by_password: false
      set_auth_cookie: true
      get_user_by_oidc: true
      force_redirect_to_identity_provider: false
    get_user_by_oidc_settings:
      client_scopes:
        - email
        - openid
      metadata_url: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_nvTFqJY2L/.well-known/openid-configuration
      # If you have a metadata URL and it returns JSON with authorization_endpoint, token_endpoint, and jwks_uri, you do
      # not need to specify those values in the configuration.
      #authorization_endpoint: https://dev-123456.okta.com/oauth2/default/v1/authorize
      #token_endpoint: https://dev-123456.okta.com/oauth2/default/v1/token
      #jwks_uri: https://dev-123456.okta.com/oauth2/default/v1/keys
      jwt_verify: true
      jwt_email_key: email
      jwt_groups_key: "cognito:groups"
      grant_type: authorization_code
      id_token_response_key: id_token
      access_token_response_key: access_token
      access_token_audience: null # Audience must not be set for Cognito
    cloud_credential_authorization_mapping:
      role_tags:
        enabled: true
        authorized_groups_tags:
          - consoleme-authorized
        authorized_groups_cli_only_tags:
          - consoleme-owner-dl
          - consoleme-authorized-cli-only
    aws:
      issuer: YourCompany
      region: "us-east-1"
    celery:
      cache_resources_from_aws_config_across_accounts:
        enabled: false
    groups:
      can_edit_config:
        - configeditors@example.com
      can_admin_policies:
        - consoleme_admins@example.com
    jwt:
      email_key: email
    jwt_secret: usafasdfTp4`sSf-6E8\RAA
    support_contact: consoleme-support@example.com
    support_chat_url: https://www.example.com/slack/channel
    documentation_page: https://github.com/Netflix/consoleme/
