version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 2048
    mem_limit: 4GB
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0661531a5841a1af7
        - subnet-03326ba1edea63961
      security_groups:
        - sg-09bc5f71409be47e6
      assign_public_ip: ENABLED
