exports_files([
    "__init__.py",
    "conftest.py",
    "globals.py",
])

py_library(
    name = "lib",
    srcs = [
        "__init__.py",
        "conftest.py",
        "globals.py",
        "util.py",
    ],
    visibility = ["//visibility:public"],
)