exports_files([
    "fixtures.py",
    "globals.py",
])

py_library(
    name = "lib",
    srcs = [
        "fixtures.py",
        "globals.py",
        "util.py",
    ],
    visibility = ["//visibility:public"],
)