load("@cloudumi_python_ext//:requirements.bzl", "requirement")
load("//util/tests:defs.bzl", "pytest_test")

# pytest_test(
#     name = "test_auth",
#     data = [
#         "//configs/development_account:configs",
#     ],
#     srcs = [
#         "test_auth.py",
#     ],
    # deps = [
    #     "//util/tests:test_dependencies_lib",
    # ],
# )

# pytest_test(
#     name = "test_celery_tasks",
#     data = [
#         "//configs/development_account:configs",
#     ],
#     srcs = [
#         "test_celery_tasks.py",
#     ],
    # deps = [
    #     "//util/tests:test_dependencies_lib",
    #],
# )
