name: GitVersion
on:
  pull_request_target:
    types:
      - closed
jobs:
  auto_version:
    name: Git Version Automation and Tagging Release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
      - name: Get commit message
        id: get_commit_message
        run: |
          if   [[ '${{ github.event_name }}' == 'push' ]]; then
            echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD)
          elif [[ '${{ github.event_name }}' == 'pull_request' ]]; then
            echo ::set-output name=commit_message::$(git log --format=%B -n 1 HEAD^2)
          fi
      - uses: 8BitJonny/gh-get-current-pr@1.3.0
        continue-on-error: true
        id: PR
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Verbose setting SHA when using Pull_Request event trigger to fix #16
          sha: ${{ github.event.pull_request.head.sha }}
          # Only return if PR is still open
          filterOutClosed: true
      - run: echo "Your PR is ${prNumber} and its JSON is ${prJSON}"
        if: success() && steps.PR.outputs.number
        env:
          prNumber: ${{ steps.PR.outputs.number }}
          # JSON object with the full PR object
          prJSON: ${{ steps.PR.outputs.pr }}
          # Direct access to common PR properties
          prUrl: ${{ steps.PR.outputs.pr_url }}
          prTitle: ${{ steps.PR.outputs.pr_title }}
          prBody: ${{ steps.PR.outputs.pr_body }}
          prCreatedAt: ${{ steps.PR.outputs.pr_created_at }}
          prMergedAt: ${{ steps.PR.outputs.pr_merged_at }}
          prClosedAt: ${{ steps.PR.outputs.pr_closed_at }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.GITVERSION_SEMVER }}
          release_name: ${{ env.prTitle }}
          body: ${{ env.prBody }}
          draft: false
          prerelease: false
