versionSpec:
  description: Required version in the form of 5.x or exact version like 5.0.0.
  required: true
  default: ''
includePrerelease:
  description: Include pre-release versions when matching a version.
  required: false
  default: false
steps:
  - name: Install GitVersion
    uses: gittools/actions/gitversion/setup@v0.9.7
    with:
      versionSpec: '5.x'
  - name: Checkout
    uses: actions/checkout@v2
    with:
      fetch-depth: 0
  - name: Determine Version
    uses: gittools/actions/gitversion/execute@v0.9.7
  - name: Display SemVer
    run: |
      echo "SemVer: $GITVERSION_SEMVER"
