name: Publish to prod using Docker
on: workflow_dispatch
# The  below will trigger build on any push to main branch
#on:
#  push:
#    branches: main
#    tags:
#      - "*"
jobs:
  deploy_to_prod:
    runs-on: self-hosted
    name: Deploy to Prod
    if: github.repository == 'noqdev/cloudumi'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches tags, which we need to determine version
      - name: Push all the things
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install \
            python3.11-dev \
            python3-pip \
            python3.11-venv -y
          curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
          sudo sh /tmp/get-docker.sh
          rm /tmp/get-docker.sh
          mkdir -p /tmp/env
          python3.11 -m venv /tmp/env
          source /tmp/env/bin/activate
          pip install boto3 pyyaml
          export AWS_ACCESS_KEY_ID=${{ secrets.NOQ_ECR_USER_PROD_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.NOQ_ECR_USER_PROD_SECRET_ACCESS_KEY }}
          export IAMBIC_REPO_USER=${{ secrets.IAMBIC_REPO_USER }}
          export IAMBIC_REPO_TOKEN=${{ secrets.IAMBIC_REPO_TOKEN }}
          export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
          deploy/infrastructure/live/shared/prod-1/push_all_the_things.sh
