name: Publish to staging using Docker
on: workflow_dispatch
# The  below will trigger build on any push to main branch
#on:
#  push:
#    branches: main
#    tags:
#      - "*"
jobs:
  deploy_to_staging:
    runs-on: self-hosted
    name: Deploy to Staging
    if: github.repository == 'noqdev/cloudumi'
    steps:
      - uses: actions/checkout@v2
      - name: Push all the things
        run: |
          set -x
          export AWS_ACCESS_KEY_ID=${{ secrets.NOQ_ECR_USER_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.NOQ_ECR_USER_SECRET_ACCESS_KEY }}
          export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
          deploy/infrastructure/live/shared/staging-1/push_all_the_things.sh
